name: CI (pull-requests-only jobs)

on:
  pull_request:
    branches:
      - master

jobs:
  buildsh:
    env:
        DEVELOPER_DIR: /Applications/Xcode_26.0.1.app/Contents/Developer
    strategy:
      matrix:
        mode: [cocoapods-lint-default-subspecs, cocoapods-lint-other-subspecs]
        include:
          - mode: cocoapods-lint-default-subspecs
            name: Verify that default subspecs lint
          - mode: cocoapods-lint-other-subspecs
            name: Verify that other subspecs lint
    name: ${{ matrix.name }}
    runs-on: macos-15
    steps:
    - name: Checkout the Git repository
      uses: actions/checkout@v4
    - name: Run build script
      run: ./build.sh ${{ matrix.mode }}
